name: esamudaayapp
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3
  modal_progress_hud: ^0.1.3
  shared_preferences: ^0.5.6+2
  flutter_redux_dev_tools: ^0.4.0
  flutter_offline: ^0.3.0
  path_provider: any
  http: ^0.12.0+4
  dio: ^3.0.8
  connectivity: ^0.4.8+1
  intl: ^0.16.0
  easy_alert: ^0.0.8
    #  flutter_secure_storage: ^3.3.1+1
  carousel_slider: ^1.4.1
  flutter_country_picker: ^0.1.6
  redux_persist_flutter: ^0.8.2
  cached_network_image: ^2.0.0
    #  cached_network_image: ^1.1.3
  equatable: ^1.1.0
  async_redux: ^2.5.4
  flutter_slidable: ^0.5.4
  easy_localization: ^2.1.0+2
  regexed_validator: ^1.0.2
  fluttertoast: ^4.0.1
  expandable: ^4.1.3
  dio_cookie_manager: ^1.0.0
  cookie_jar: ^1.0.1
  google_maps_place_picker: ^0.9.4
  flutter_rating_bar: ^3.0.1+1
  firebase_messaging: ^6.0.15
  date_format: ^1.0.8
  image_picker:

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  fonts:
    - family: Avenir
      fonts:
        - asset: assets/font/Avenir-Book.ttf

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/languages/en-US.json
    - assets/languages/ka-IN.json
    - assets/languages/ml-IN.json
    - assets/images/Component 6 – 1.png
    - assets/images/app_main_icon.png
    - assets/images/location_1_add.png
    - assets/images/bag2.png
    - assets/images/location2.png
    - assets/images/notification.png
    - assets/images/path5.png
    - assets/images/path330.png
    - assets/images/path338.png
    - assets/images/search_icon.png
    - assets/images/fruits.png
    - assets/images/banner.png
    - assets/images/delivery.png
    - assets/images/no_delivery.png
    - assets/images/shop1.png
    - assets/images/shop2.jpg
    - assets/images/fruits.jpg
    - assets/images/dairy-products.jpg
    - assets/images/groceries.jpg
    - assets/images/medicine.jpg
    - assets/images/soft-drink.jpg
    - assets/images/snack.jpg
    - assets/images/home41.png
    - assets/images/Group_240.png
    - assets/images/power.png
    - assets/images/clipart.png
    - assets/images/AI_user.png
    - assets/images/question_cr.png
    - assets/images/AI_chat.png
    - assets/images/user.jpg
    - assets/images/align2.png
    - assets/images/pen2.png
    - assets/images/group236.png


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
