import 'package:esamudaayapp/modules/home/models/merchant_response.dart';
import 'package:esamudaayapp/modules/orders/models/order_models.dart';
import 'package:esamudaayapp/modules/store_details/models/catalog_search_models.dart';

class Autogenerated {
  List<ItemsEnhanced> itemsEnhanced;
  String service;
  int total;

  Autogenerated({this.itemsEnhanced, this.service, this.total});

  Autogenerated.fromJson(Map<String, dynamic> json) {
    if (json['itemsEnhanced'] != null) {
      itemsEnhanced = new List<ItemsEnhanced>();
      json['itemsEnhanced'].forEach((v) {
        itemsEnhanced.add(new ItemsEnhanced.fromJson(v));
      });
    }
    service = json['service'];
    total = json['total'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    if (this.itemsEnhanced != null) {
      data['itemsEnhanced'] =
          this.itemsEnhanced.map((v) => v.toJson()).toList();
    }
    data['service'] = this.service;
    data['total'] = this.total;
    return data;
  }
}

class ItemsEnhanced {
  Product item;
  int number;

  ItemsEnhanced({this.item, this.number});

  ItemsEnhanced.fromJson(Map<String, dynamic> json) {
    item = json['item'] != null ? new Product.fromJson(json['item']) : null;
    number = json['number'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    if (this.item != null) {
      data['item'] = this.item.toJson();
    }
    data['number'] = this.number;
    return data;
  }
}

class PlaceOrderRequest {
  String phoneNumber;
  Orders order;
  String comments;

  PlaceOrderRequest({this.phoneNumber, this.order, this.comments});

  PlaceOrderRequest.fromJson(Map<String, dynamic> json) {
    phoneNumber = json['phoneNumber'];
    order = json['order'] != null ? new Orders.fromJson(json['order']) : null;
    comments = json['comments'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['phoneNumber'] = this.phoneNumber;
    if (this.order != null) {
      data['order'] = this.order.toJson();
    }
    data['comments'] = this.comments;
    print(data);
    return data;
  }
}

class PlaceOrderResponse {
  Order order;

  PlaceOrderResponse({this.order});

  PlaceOrderResponse.fromJson(Map<String, dynamic> json) {
    order = json['order'] != null ? new Order.fromJson(json['order']) : null;
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    if (this.order != null) {
      data['order'] = this.order.toJson();
    }
    return data;
  }
}

class ServiceSpecificData {
  double dELIVERYCHARGE;

  ServiceSpecificData({this.dELIVERYCHARGE});

  ServiceSpecificData.fromJson(Map<String, dynamic> json) {
    dELIVERYCHARGE = json['DELIVERY_CHARGE'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['DELIVERY_CHARGE'] = this.dELIVERYCHARGE;
    return data;
  }
}

class Order {
  Cart cart;
  bool codPaymentCompleted;
  String merchantID;
  String paymentType;
  Map serviceSpecificData;
  double totalOrderCost;
  Address address;
  Order(
      {this.cart,
      this.address,
      this.codPaymentCompleted,
      this.merchantID,
      this.paymentType,
      this.serviceSpecificData,
      this.totalOrderCost});

  Order.fromJson(Map<String, dynamic> json) {
    cart = json['cart'] != null ? new Cart.fromJson(json['cart']) : null;
    address =
        json['address'] != null ? new Address.fromJson(json['address']) : null;
    codPaymentCompleted = json['codPaymentCompleted'];
    merchantID = json['merchantID'];
    paymentType = json['paymentType'];
    serviceSpecificData = json['serviceSpecificData'];
    totalOrderCost = json['totalOrderCost'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    if (this.cart != null) {
      data['cart'] = this.cart.toJson();
    }
    if (this.address != null) {
      data['address'] = this.address.toJson();
    }
    data['codPaymentCompleted'] = this.codPaymentCompleted;
    data['merchantID'] = this.merchantID;
    data['paymentType'] = this.paymentType;
    if (this.serviceSpecificData != null) {
      data['serviceSpecificData'] = this.serviceSpecificData;
    }
    data['totalOrderCost'] = this.totalOrderCost;
    return data;
  }
}

class Cart {
  List<ItemsEnhanced> itemsEnhanced;
  String service;
  double total;

  Cart({this.itemsEnhanced, this.service, this.total});

  Cart.fromJson(Map<String, dynamic> json) {
    if (json['itemsEnhanced'] != null) {
      itemsEnhanced = new List<ItemsEnhanced>();
      json['itemsEnhanced'].forEach((v) {
        itemsEnhanced.add(new ItemsEnhanced.fromJson(v));
      });
    }
    service = json['service'];
    total = json['total'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    if (this.itemsEnhanced != null) {
      data['itemsEnhanced'] =
          this.itemsEnhanced.map((v) => v.toJson()).toList();
    }
    data['service'] = this.service;
    data['total'] = this.total;
    return data;
  }
}
